### PR TITLE
src: introduce --trust-environment option for 'rauc convert'

### LINKED ISSUE #679: casync bundle creation fails with "unable to find mounted device for bundle" when building inside container
Since RAUC version 1.5 creating casync bundles no longer works. This is the relevant output when the `bundle.bbclass` executes the convert command to create the casync bundle:
```
rauc-Message: 13:21:55.950: Debug log domains: 'rauc'
(rauc:34224): rauc-DEBUG: 13:21:55.951: convert start
(rauc:34224): rauc-DEBUG: 13:21:55.951: system config not found, using default values
rauc-Message: 13:21:55.951: Failed to resolve realpath for '/dev/disk/by-uuid/be5faaeb-1680-4ca2-af65-f30f06dab903'
(rauc:34224): rauc-DEBUG: 13:21:55.951: input bundle: /home/user/documents/yocto/imx6ul/dunfell/build/tmp/work/machine/headless-bundle/1.0-r0/build/bundle.raucb
(rauc:34224): rauc-DEBUG: 13:21:55.951: output bundle: /home/user/documents/yocto/imx6ul/dunfell/build/tmp/work/machine/headless-bundle/1.0-r0/build/casync-bundle.raucb
rauc-Message: 13:21:55.951: Reading bundle: /home/user/documents/yocto/imx6ul/dunfell/build/tmp/work/machine/headless-bundle/1.0-r0/build/bundle.raucb
rauc-Message: 13:21:55.952: Verifying bundle signature...
(rauc:34224): rauc-DEBUG: 13:21:55.952: initial check_bundle_access failed with: unable to find mounted device for bundle
unable to find mounted device for bundle
WARNING: exit code 1 from a shell command.
```
I am looking at the code changes that version 1.5 brings but I do not really understand yet what the exact issue is with this one. AFAIK `check_bundle_access()` checks several parameters to prevent unintended write access to the bundle. Though I am unsure which device the error message is referring to and what is wrong with it.

### PR DESCRIPTION
**Pull request by ejoerns**
In some cases it might not be possible or wanted that RAUC (used as a host tool) performs its standard bundle access checks.

For example when running 'rauc convert' from within a (docker) container, RAUC might not be able to get the underlying device of the bundle's storage location. This way it cannot determine if the mount point is owend by root and will abort with

> initial check_bundle_access failed with: unable to find mounted device for bundle

While --no-verify potentially already works around this, it is a too big hammer for most cases where you actually want to benefit from the usual signature verificaton of the input bundle and just get stopped by the exclusiv access check.

Not the --trust-environment option allows to tell RAUC that we assume we have our environmet we run RAUC in under control and it can skip the exclusive access checks.

Fixes #679, #688

Note: bases on #769

### CODE REVIEW

**Comment by mschwan-phytec** [comment]
Thanks for adding this option. :+1: I tried this in one of our Docker build containers and `rauc convert --trust-environment ...` now works without any issues. From my side, this then fixes #679.

**Comment by mschwan-phytec** [comment]
@ejoerns Any update on these PRs? I would really like to see this being merged soon. :slightly_smiling_face:

**Comment by ejoerns** [comment]
Unfortunately, @mschwan-phytec no update from my side, yet. I would like to know what @jluebbe thinks about this first of all. He's currently digging through other rauc-related topics and will hopefully arrive here soon ;)

File: src/main.c [hunk 1]
```diff
@@ -495,7 +496,7 @@ static gboolean resign_start(int argc, char **argv)
 		goto out;
 	}
 
-	if (!check_bundle(argv[2], &bundle, !verification_disabled, &ierror)) {
+	if (!check_bundle(argv[2], &bundle, !verification_disabled, FALSE, &ierror)) {
```
Comment (jluebbe) [inline src/main.c:499]: For parameters that are essential for security, I find this hard to read (especially `, TRUE, FALSE,` or `, FALSE, FALSE` below). How about using a flags enum for this? `R_CHECK_DISABLE_VERIFICATION` and `R_CHECK_TRUST_ENVIRONMENT` for now?

I thought about creating the bundle struct outside of `check_bundle` with parameters, but I quite like that you need to call `check_bundle` to get a bundle struct in the current code.

Comment (ejoerns) [reply src/main.c:499]: +1 for struct from my side. I actually already thought about this too, as I always had to check what 'FALSE' and 'TRUE' actually meant.

Comment (ejoerns) [reply src/main.c:499]: "+1 for Enum" I meant of course. :smirk:

Comment (jluebbe) [reply src/main.c:499]: @ejoerns What do you think about building this on https://github.com/rauc/rauc/pull/462 instead?

Comment (jluebbe) [reply src/main.c]: I've rebased this on after the merge of #462, which simplified this significantly.

**Comment by ejoerns** [comment]
@jluebbe  Should we then drop #769 in favor of this combined rebase?

**Comment by ejoerns** [comment]
Just fixed some typos in my commit message.

**Comment by ejoerns** [comment]
Added missing man page update for `--trust-environment`.

**Comment by jluebbe** [comment]
> @jluebbe Should we then drop #769 in favor of this combined rebase?

I don't see much use in merging that separately.

**Comment by ejoerns** [comment]
Cannot approve my own PR in GH, but FTR: looks fine for me now. Thx @jluebbe for the rework.

**Review by jluebbe — APPROVED** [review]
