### PR TITLE
Simplify and Fix Bootslot Handling

### LINKED ISSUE #1360: Service fails to start with an assertion error in r_slot_status_load() after updating from v1.10.1 to v1.11.2
rauc service fails with an assertion error in r_slot_status_load() as it get called with a NULL pointer after updating to rauc v1.11.2. The same config works on v1.10.1 without issues.

v.10.1 log (booted B):
```
rauc service -d
rauc-Message: 09:00:01.613: Debug log domains: 'rauc'
rauc-Message: 09:00:01.617: Using central status file /mnt/data/rauc.status
(rauc:608): rauc-DEBUG: 09:00:01.618: Resolved bootname /dev/disk/by-partlabel/root-b to /dev/mmcblk0p6
(rauc:608): rauc-DEBUG: 09:00:01.618: Obtained system boot ID: 'd61f5b03-7a2b-47e2-b8b8-d0d831d98060'
rauc-INFO: 09:00:01.618: Failed to get machine-id: Failed to open file ?/etc/machine-id?: No such file or directory
(rauc:608): rauc-DEBUG: 09:00:01.618: Obtained system machine ID: '(null)'
(rauc:608): rauc-DEBUG: 09:00:01.618: service start
(rauc:608): rauc-DEBUG: 09:00:01.618: Found booted slot: rootfs.1 on /dev/disk/by-partlabel/root-b
(rauc:608): rauc-DEBUG: 09:00:01.624: name 'de.pengutronix.rauc' acquired
```

v1.11.2 (booted A):
```
rauc service -d
rauc-Message: 08:55:17.867: Debug log domains: 'rauc'
rauc-Message: 08:55:17.871: Using central status file /mnt/data/rauc.status
(rauc:7771): rauc-DEBUG: 08:55:17.872: Resolved bootname /dev/disk/by-partlabel/root-a to /dev/mmcblk0p4
(rauc:7771): rauc-DEBUG: 08:55:17.872: Obtained system boot ID: 'a69a02de-b0f8-47e9-826e-7be061411eb3'
rauc-INFO: 08:55:17.872: Failed to get machine-id: Failed to open file ?/etc/machine-id?: No such file or directory
(rauc:7771): rauc-DEBUG: 08:55:17.872: Obtained system machine ID: '(null)'
(rauc:7771): rauc-DEBUG: 08:55:17.872: service start
(rauc:7771): rauc-DEBUG: 08:55:17.873: Found booted slot: rootfs.0 on /dev/disk/by-partlabel/root-a

(rauc:7771): rauc-CRITICAL **: 08:55:17.873: r_slot_status_load: assertion 'dest_slot' failed
Trace/breakpoint trap
```

system.conf is:
```
cat /etc/rauc/system.conf
[system]
compatible=gaia-300d-r1
mountprefix=/run/rauc
statusfile=/mnt/data/rauc.status
bootloader=custom
bundle-formats=-plain
max-bundle-download-size=120000000

[keyring]
path=/etc/rauc/keyring.pem
use-bundle-signing-time=true

[encryption]
key=/etc/rauc/bundle-key.pem

[handlers]
bootloader-custom-backend=/usr/sbin/rauc-custom-boot-handler
post-install=/usr/sbin/rauc-post-install

[slot.boot.0]
device=/dev/disk/by-partlabel/boot
type=raw

[slot.rootfs.0]
device=/dev/disk/by-partlabel/root-a
type=raw
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/root-b
type=raw
bootname=B

[slot.kernelfs.0]
device=/dev/disk/by-partlabel/kernel-a
type=raw
parent=rootfs.0

[slot.kernelfs.1]
device=/dev/disk/by-partlabel/kernel-b
type=raw
parent=rootfs.1
```

Adding a few printf statements I see that I end up in the `r_context()->system_status` conditional in `service_start()` (as system.statusfile is set) where it tries to match `r_context()->bootslot (/dev/mmcblk0p4)` with the slot device names by `r_slot_find_by_device()`. The problem here is that those refer to the `/dev/disk/by-partlabel/*` symlinks so dumb strcmp with `/dev/mmcblk0p4` naturally fails and we end up calling `r_slot_status_load(NULL)`.

How is this supposed to work and why is trying to redo the work done in determine_slot_states() (which correctly resolved the symlink to /dev/mmcblk0p4, see the log above).

### PR DESCRIPTION
**Pull request by ejoerns**
* Introduces a helper `r_slot_get_booted()` to get the determined boot slot
* Replace indirect re-determination of bootslot
* remove obsolete helper `r_slot_find_by_bootname()` then

Fixes #1360

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -2123,9 +2123,7 @@ static gboolean service_start(int argc, char **argv)
 			if (g_strcmp0(r_context()->bootslot, "_external_") == 0) {
 				r_event_log_booted_external();
 			} else {
-				RaucSlot *booted_slot = r_slot_find_by_device(r_context()->config->slots, r_context()->bootslot);
-				if (!booted_slot)
-					booted_slot = r_slot_find_by_bootname(r_context()->config->slots, r_context()->bootslot);
+				RaucSlot *booted_slot = r_slot_get_booted(r_context()->config->slots);
```
Comment (jacmet) [inline src/main.c:2124]: Do we still need the "_external_" workaround from 2928ac0603a77c7e817d541f6a872fc81ad59258 then?

Comment (ejoerns) [reply src/main.c:2124]: Yes, since for *external*, there is no real 'booted' slot that we can get.

When I originally implemented the surrounding code, I used an approach that generated a dummy slot for the 'external' case. With this, the special handling for *external* would have been obsolete. But this was dropped during review since it might have had other impact.

Comment (jacmet) [reply src/main.c:2124]: ok, thanks

**Review by jluebbe — APPROVED** [review]

**Comment by jacmet** [comment]
@jluebbe it would also be great if this could get merged to stable-1.11 (it applies without fuzz) and included in an upcoming 11.3 release

**Comment by jluebbe** [comment]
> @jluebbe it would also be great if this could get merged to stable-1.11 (it applies without fuzz) and included in an upcoming 11.3 release

I've released [v1.11.3](https://github.com/rauc/rauc/releases/tag/v1.11.3) with this fix.
