### PR TITLE
src/main: fix and add support for boot detection with rauc.external

### LINKED ISSUE #1313: Rauc service core dump on 1.11
**Describe the bug**
Rauc service core dump running from external media (USB) (first install scenario)

**Background information**
1.11

**To Reproduce**
Boot

**Expected behavior**
Service should run (ok on 1.10.1)

**Logs**
```
Jan 05 07:09:21 dr-imx8mp systemd[1]: Starting RAUC Update Service...
Jan 05 07:09:21 dr-imx8mp rauc[698]: Using central status file /service/rauc/status
Jan 05 07:09:21 dr-imx8mp rauc[698]: Failed to load system status: No such file or directory
Jan 05 07:09:21 dr-imx8mp rauc[698]: Getting Systeminfo: /usr/lib/rauc/info-provider.sh
Jan 05 07:09:21 dr-imx8mp rauc[698]: Detected explicit external boot, ignoring missing active slot
Jan 05 07:09:21 dr-imx8mp rauc[698]: r_slot_status_load: assertion 'dest_slot' failed
Jan 05 07:09:21 dr-imx8mp systemd[1]: rauc.service: Main process exited, code=dumped, status=5/TRAP
Jan 05 07:09:21 dr-imx8mp systemd[1]: rauc.service: Failed with result 'core-dump'.
Jan 05 07:09:21 dr-imx8mp systemd[1]: Failed to start RAUC Update Service.
```

**Additional context**
Boots from USB stick targeting install on eMMC

### PR DESCRIPTION
**Pull request by ejoerns**
The current boot detection handling did not take into account that there is no booted slot when using `rauc.external` in cmdline and called `r_slot_status_load()` with `NULL` argument causing a

    (rauc:676): rauc-CRITICAL **: 16:16:16.336: r_slot_status_load: assertion 'dest_slot' failed

Fix this by explicitly checking for external boot and also emit a dedicated log message since this might be relevant for the log, too.

Fixes #1313
Fixes b9e4cdce0879862126aeb786bdd7f6672e392ca9 ("src/main: log boot and service restart")

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -2078,12 +2096,17 @@ static gboolean service_start(int argc, char **argv)
...
+			} else {
+				RaucSlot *booted_slot = r_slot_find_by_device(r_context()->config->slots, r_context()->bootslot);
+				if (!booted_slot)
+					booted_slot = r_slot_find_by_bootname(r_context()->config->slots, r_context()->bootslot);
 
-			r_event_log_booted(booted_slot);
+				r_slot_status_load(booted_slot);
+
+				r_event_log_booted(booted_slot);
+			}
```
Comment (jluebbe) [inline src/main.c:2109]: Shouldn't we try to handle the case where we still can't find the booted slot?

We may not be able to install in that state, but `rauc info` should still work.

**Review by jluebbe — CHANGES_REQUESTED** [review]

File: src/main.c (hunk 1 above)
Comment (ejoerns) [reply src/main.c:2109]: I've thought about this, too but did not find a proper handling.

If the slot is invalid, the service will abort anyway with

    Failed to determine slot states: Did not find booted slot (matching 'XYZ')

In how far do you mean that `rauc info` will not work? It does not use the service, thus this should be unrelated.

**Review by jluebbe — APPROVED** [review]
